### PR TITLE
Use ingredients in month style instead of quarter

### PR DESCRIPTION
**Pull request by jido**

### CODE REVIEW

**Review by jvraines — COMMENTED** [review]
Thanks for your suggestion. When you propose a change, please leave a comment explaining what you are trying to accomplish.

What is the purpose of `GetMonthStyle`? What does it do that `GetQuarter` doesn't?

**Comment by jido** [comment]
The intention is to use "ingredients" in the month style (= starting Monday, starting Wednesday, starting Thursday or starting Friday) instead of the quarter. The value is different from the quarter value.

**Comment by jido** [comment]
It is related to a recent update to the calendar: https://calendars.fandom.com/wiki/Hawaiian_Slice_Calendar?diff=14149&oldid=14141

**Comment by jvraines** [comment]
I see. This is a change to your calendar design after I had included it. "Style" is pretty vague. Can we call it `GetMonthIngredient` instead?  With "i" as the special format code?
Now I want some pizza. ;-)

**Comment by jido** [comment]
Yes you can, I would love it!

**Comment by jvraines** [comment]
I will push again in a little while after I test and clean up the change.

**Pull request merged**
